#!/bin/sh
set -e

BUILD_TYPE="Debug"
LOG_LEVEL="DEBUG"
ENABLE_NATIVE="OFF"

while getopts "t:l:nh" opt; do
  case "$opt" in
    t) BUILD_TYPE="$OPTARG" ;;
    l) LOG_LEVEL="$OPTARG" ;;
    n) ENABLE_NATIVE="ON" ;;
    h|\?)
      echo "Использование: $0 [-t BUILD_TYPE] [-l LOG_LEVEL] [-n]"
      echo "  -t  Тип сборки: Debug (по умолч.), Release, RelWithDebInfo"
      echo "  -l  Уровень логов: TRACE, DEBUG (по умолч.), INFO, WARN, ERROR, OFF"
      echo "  -n  Включить оптимизацию под текущий CPU (-march=native)"
      exit 0
      ;;
  esac
done

case "$LOG_LEVEL" in
  SPDLOG_LEVEL_*) FULL_LOG_LEVEL="$LOG_LEVEL" ;;
  *)               FULL_LOG_LEVEL="SPDLOG_LEVEL_$(echo "$LOG_LEVEL" | tr '[:lower:]' '[:upper:]')" ;;
esac

echo "==> Сборка: TYPE=$BUILD_TYPE | LOG=$FULL_LOG_LEVEL | NATIVE=$ENABLE_NATIVE"

cmake -B build -G Ninja \
  -DCMAKE_BUILD_TYPE="$BUILD_TYPE" \
  -DSPDLOG_ACTIVE_LEVEL="$FULL_LOG_LEVEL" \
  -DENABLE_NATIVE="$ENABLE_NATIVE"

cmake --build build
